name: Daily Snapshot to Google Sheets

on:
  schedule:
    - cron: '1 0 * * *'  # ogni giorno alle 00:01 UTC
  workflow_dispatch:     # puoi avviarlo anche manualmente

jobs:
  run_snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install gspread oauth2client

      - name: Create creds.json from secret
  run: |
    echo "${{ secrets.GOOGLE_CREDS_JSON }}" | base64 --decode > creds.json

      - name: Run snapshot script
        run: python snapshot_scheduler.py



